### ISSUE TITLE
Untagged union

### ISSUE THREAD

**Issue by edobrb** [twinlogix/mondrian-framework#89]
We should consider supporting untagged union in order to be as expressive as openapi. At the moment Mondrian cannot support a simple union like `string | number | ...` meanwhile in openapi it is possible. 

Example scenarios where this feature is required:
 - To proxy an existing service with this framework and the underling API uses untagged union.
 - A function must accept two different input (i.e a untagged union) in order to be retro compatible.
 
Some critical points:
 - if the union type is used as output type the projection could exclude the minimum information to discriminate the variants
  ```typescript
const user = types.union({
    manager: types.object({ type: types.literal('manager'), name: types.string() }),
    customer: types.object({ type: types.literal('customer'), name: types.string() })
})
// projection { manager: { name: true }, customer: { name: true } }
 ```
 In this case we could decorate the given projection with the complete fields set if the varian type is a object type
 - decoding with 'tryCasting'
 ```typescript
const u = types.union({ number: types.number(), string: types.string() })
const result = u.decode("25", { typeCastingStrategy: 'tryCasting' })
// result.value should be "25" and not 25. (The cast should be avoided if not necessary)
 ```
In this case we should try to decode without casting before and then try to cast if no variants can decode.

Bonus: with untagged union we automatically supports tagged union (with different formats)
```typescript
// { string: string } | { number: number }
const taggedUnion = types.union({ 
    v1: types.object({ string: types.string() }), 
    v2: types.object({ number: types.number() })
}) 
// { type: 'string', value: string } | { type: 'number', value: number }
const taggedUnion = types.union({ 
    v1: types.object({ type: types.literal('string'), value: types.string() }), 
    v2: types.object({ type: types.literal('number'), value: types.number() })
})
```

**Comment by edobrb** [comment]
Maybe we could just extends the union type with an options `'tagged' | 'untagged'` and by default it's `'tagged'`.
This will change the encode, validate and decode behaviour.

```typescript
const u = types.union({ v1: types.number(), v2: types.string() }, 'untagged')
type U = types.Infer<typeof u> // { v1: number } | { v2: string }

const result = u.decode(123) // ok -> { v1: 123 }
u.encode({ v1: 123 }) // ok -> 123
```

**Comment by giacomocavalieri** [comment]
I hope this series of bullet points can be helpful to keep track of the design choices we'll have to make to add untagged unions into Mondrian's type system.

### 1. Discriminating unions when encoding/decoding?

Being untagged, we would have to add back the `minimumRequiredProjection`/`isVariant`/`...` fields to the union type, since there is no automatic way to tell a variant from the others.

However, this raises a couple of questions (that was the reason we first decided to remove those) and I don't know how those could be addressed. I'm curious to hear your opinion @edobrb , @minox86 .

### 2. Ease of use

I believe those fields make the union definition quite cumbersome. Let me make an example:

```ts
// tagged union
const response = types.union({ ok: types.number(), error: types.string() })
```

as opposed to:

```ts
// untagged version
const response = types.union({
  variants: {
    ok: types.object({ type: types.literal("ok"), value: types.number() }),
    error: types.object({ type: types.literal("error"), value: types.string() })
  },
  // Basically the developer has to manually tag the unions in an ad-hoc way
  isVariant: {
    ok: (value) => value.type === "ok",
    error: (value) => value.type === "error"
  },
  minimumRequiredProjection: { type: true }
})
```

This would make the code way more verbose, prone to bugs and altogether hinder the adoption of unions in a codebase that is using Mondrian.

We could take inspiration from Zod's approach here but I'm not sure how applicable that is to our use case, especially with mutually recursive types.


### 3. Serialisation/deserialisation

The presence of a field like `isVariant` would make it impossible to serialise/deserialise a union. It's basically the same problem we are having with custom data types.

The main difference is that we can implement some special handling for some library defined custom types like `DateTime` while it wouldn't be possible to do the same for user defined unions

### 4. Performance

This is not a huge concern on my part but I think it's worth pointing it out anyways.
With the `isVariant` encoding/decoding must be performed in a sequence of steps, trying each decoder in sequence. If one fails, the following one is tried until a valid decoder is found among the ones in `isVariant`.

```ts
const union = types.union({
  variants: { v1: types.number(), v2: types.number() },
  isVariant: {
    v1: expensiveFunction,
    v2: ...,
  }
})
```

All calls to decode would incur in the overhead introduced by `expensiveFunction`, no matter which variant the value actually belongs to. With tagged variants we have a constant time way to tell if something belongs to a variant or not.

**Comment by giacomocavalieri** [comment]
> Maybe we could just extends the union type with an options `'tagged' | 'untagged'` and by default it's `'tagged'`. This will change the encode, validate and decode behaviour.
> 
> ```ts
> const u = types.union({ v1: types.number(), v2: types.string() }, 'untagged')
> type U = types.Infer<typeof u> // { v1: number } | { v2: string }
> 
> const result = u.decode(123) // ok -> { v1: 123 }
> u.encode({ v1: 123 }) // ok -> 123
> ```

In this example you are showing a tagged union though, the inferred type has the variant tag. What would the code look like with an untagged one?

**Comment by edobrb** [comment]
My suggestion is to keep the variant tag inside our runtime but giving the ability to decode/encode from an untagged union. On #90 I've implemented this behaviour.
